services:
  drivers_postgresql:
    container_name: ms_drivers_pg_sql
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: drivers
    volumes:
      - drivers_psql:/data/postgres
    ports:
      - "5433:5432"
    networks:
      - microservices-net
    restart: unless-stopped

  passengers_postgresql:
    container_name: ms_passengers_pg_sql
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: passengers
    volumes:
      - passengers_psql:/data/postgres
    ports:
      - "5434:5432"
    networks:
      - microservices-net
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INIT_DB_ROOT_USERNAME: root
      MONGO_INIT_DB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: ride-db
    volumes:
      - mongo_data:/data/db
networks:
  microservices-net:
    driver: bridge
volumes:
  drivers_psql:
  passengers_psql:
  mongo_data:


