server:
  port: 8222
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: driver-service
          uri: lb:http://DRIVER-SERVICE
          predicates:
            - Path=/api/v1/test/**